# Generated by Django 4.2.18 on 2025-01-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('model', models.IntegerField()),
                ('company', models.CharField(max_length=200)),
                ('km', models.IntegerField()),
            ],
        ),
    ]
