# Generated by Django 4.2.18 on 2025-01-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carAgency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cars',
        ),
    ]
